import itertools
import itertools as it
from typing import Dict, List, Optional, Set, Tuple

import numpy as np
import networkx as nx
from collections import defaultdict

def cycle_python_matrix(matrix):
    """Cycles the rows and columns of a square matrix.

    Args:
        matrix: A square matrix represented as a list of lists.

    Returns:
        The cycled matrix.
    """

    # Cycle rows
    matrix = matrix[1:] + [matrix[0]]

    # Cycle columns
    for i in range(len(matrix)):
        matrix[i] = matrix[i][1:] + [matrix[i][0]]

    return matrix

def cycle_matrix(matrix):
    """Cycles the rows and columns of a square numpy matrix."""

    # Cycle rows
    matrix = np.roll(matrix, 1, axis=0)

    # Cycle columns
    matrix = np.roll(matrix, 1, axis=1)

    return matrix

# thanks ChatGPT o1!
def three_disjoint_contiguous_sublists(N):
    """
    Return *all* triples of disjoint contiguous sublists (of length >= 1)
    in the range [0..N-1], skipping any indices we like.
    """
    results = []
    
    # Loop over the first sublist
    for start1 in range(N):
        for end1 in range(start1, N):
            # sublist1 = [start1..end1]
            A = list(range(start1, end1 + 1))
            
            # Loop over the second sublist (must start after end1)
            for start2 in range(end1 + 1, N):
                for end2 in range(start2, N):
                    # sublist2 = [start2..end2]
                    B = list(range(start2, end2 + 1))
                    
                    # Loop over the third sublist (must start after end2)
                    for start3 in range(end2 + 1, N):
                        for end3 in range(start3, N):
                            # sublist3 = [start3..end3]
                            C = list(range(start3, end3 + 1))
                            
                            results.append((A, B, C))
    
    return results

get_lists = three_disjoint_contiguous_sublists

# three_disjoint_contiguous_sublists(8)


def generate_non_overlapping_regions_v2(
    L: int,
    mingap: int = 0,
    assume_rotational_invariance: bool = False
) -> List[Tuple[List[int], List[int], List[int]]]:
    """
    Generates all unique combinations of three non-overlapping regions
    of sequential integers modulo L, with a minimum gap between regions.

    Generated by Gemini 2.5 Pro, modified by Copilot.

    Args:
        L: The total length (modulus). Must be >= 3.
        mingap: The minimum required gap between the end of one region
                and the start of the next (cyclically). Must be >= 0.
        assume_rotational_invariance: If True, assumes rotational invariance
                                      and only generates one representative
                                      configuration for each composition,
                                      skipping the L rotations. Defaults to False.

    Returns:
        A list of tuples. Each tuple contains three lists, where each list
        represents a region [start, start+1, ..., end] (mod L).
        The list contains all unique combinations, avoiding permutations
        of the same set of three regions.
    """
    # Need at least L=3 for 3 regions of length 1 (with 0 gaps)
    if not isinstance(L, int) or L < 3:
        print("L must be an integer >= 3")
        return []
    if not isinstance(mingap, int) or mingap < 0:
        raise ValueError("mingap must be a non-negative integer")

    # Use a set to automatically handle duplicates after canonicalization
    # The canonical form: tuple(sorted(tuple(region) for region in triple by start element))
    results_set: Set[Tuple[Tuple[int, ...], Tuple[int, ...], Tuple[int, ...]]] = set()

    # Map to compositions of N' into 6 positive integers (l'_1..3, g'_1..3)
    # where l_i = l'_i >= 1
    # and g_i = g'_i - 1 + mingap >= mingap
    # Sum: l1+l2+l3+g1+g2+g3 = L
    # Sum': l'_1+l'_2+l'_3+g'_1+g'_2+g'_3 = L - 3*mingap + 3
    target_sum = L - 3 * mingap + 3
    num_parts = 6

    # Check if composition is possible (need 6 parts >= 1)
    if target_sum < num_parts:
        # This happens if L < 3*mingap + 3
        # print(f"Warning: No combinations possible for L={L} and mingap={mingap}")
        return []

    # Iterate through compositions using stars and bars
    # Choose k-1=5 divider positions from n-1 = target_sum-1 possible spots
    for dividers in itertools.combinations(range(1, target_sum), num_parts - 1):
        # Calculate the value of each part (l'_1, l'_2, l'_3, g'_1, g'_2, g'_3)
        all_dividers = (0,) + dividers + (target_sum,)
        parts = [all_dividers[i+1] - all_dividers[i] for i in range(num_parts)]

        # Extract region lengths (l_i >= 1) and gap lengths (g_i >= mingap)
        l1, l2, l3 = parts[0], parts[1], parts[2]
        g1 = parts[3] - 1 + mingap
        g2 = parts[4] - 1 + mingap
        g3 = parts[5] - 1 + mingap

        # --- Construct the base configuration (starting R1 at 0) ---
        regions_base = []
        current_pos = 0

        # Region 1
        r1_list = [(current_pos + i) % L for i in range(l1)]
        if not r1_list: continue # Should not happen if l1 >= 1
        regions_base.append(r1_list)
        current_pos = (current_pos + l1 + g1) % L # Position for start of R2

        # Region 2
        r2_list = [(current_pos + i) % L for i in range(l2)]
        if not r2_list: continue # Should not happen if l2 >= 1
        regions_base.append(r2_list)
        current_pos = (current_pos + l2 + g2) % L # Position for start of R3

        # Region 3
        r3_list = [(current_pos + i) % L for i in range(l3)]
        if not r3_list: continue # Should not happen if l3 >= 1
        regions_base.append(r3_list)

        if assume_rotational_invariance:
            # --- Only canonicalize and add the base configuration ---
            try:
                # Sort the list of lists (regions) based on their numeric starting element
                sorted_regions = sorted(regions_base, key=lambda r: r[0])
                # Convert inner lists to tuples for hashability
                canonical_form = tuple(tuple(r) for r in sorted_regions)
                results_set.add(canonical_form)
            except IndexError:
                 # This guards against unforeseen empty regions, though l_i>=1 should prevent it.
                 pass
        else:
            # --- Generate all L rotations of this base configuration ---
            for shift in range(L):
                rotated_triple_list = []
                for region_list in regions_base:
                     # Apply shift and ensure elements are mod L
                     shifted_list = [(x + shift) % L for x in region_list]
                     rotated_triple_list.append(shifted_list)

                # --- Canonicalize and add to set ---
                try:
                    # Sort the list of lists (regions) based on their numeric starting element
                    sorted_regions = sorted(rotated_triple_list, key=lambda r: r[0])
                    # Convert inner lists to tuples for hashability
                    canonical_form = tuple(tuple(r) for r in sorted_regions)
                    results_set.add(canonical_form)
                except IndexError:
                     # This guards against unforeseen empty regions, though l_i>=1 should prevent it.
                     pass

    # Convert the canonical tuples back to the desired list of tuples of lists
    final_list: List[Tuple[List[int], List[int], List[int]]] = []
    for canonical_tuple in results_set:
        triple_of_lists = tuple(list(r) for r in canonical_tuple)
        final_list.append(triple_of_lists) # type: ignore

    return final_list

# --- Updated Function ---
def get_boundary_nodes_by_position(
    graph: nx.Graph,
    kept_indices: Optional[List[int]] = None
) -> Tuple[Dict[int, List[int]], List[int]]:
    """
    Identifies boundary nodes and groups their phase space indices by position.
    If kept_indices is provided, maps original indices to their position within kept_indices.

    Assumes nodes have 'is_boundary' (bool) and 'position_in_boundary' (int) attributes.
    Node indices are assumed to be the phase space indices (0 to 2N-1).

    Args:
        graph: The networkx graph.
        kept_indices: Optional list of the original phase space indices that remain after measurement.
                      If provided, the returned indices will be relative to this list.

    Returns:
        A tuple containing:
        - A dictionary mapping boundary position -> sorted list of phase space node indices
          (relative to kept_indices if provided, otherwise original).
        - A sorted list of unique boundary positions found among the kept nodes.
    """
    boundary_nodes_map = defaultdict(list)
    positions = set()

    # Create a lookup for fast checking if an index is kept and its new position
    kept_indices_lookup = {original_idx: new_idx for new_idx, original_idx in enumerate(kept_indices)} if kept_indices is not None else None

    for node, data in graph.nodes(data=True):
        if data.get('is_boundary', False):
            position = data.get('position_in_boundary')
            if position is not None:
                # Node index 'node' is the original phase space index
                original_phase_space_index = node

                if kept_indices_lookup is not None:
                    # Check if this boundary node's index is in the kept indices
                    if original_phase_space_index in kept_indices_lookup:
                        new_index = kept_indices_lookup[original_phase_space_index]
                        boundary_nodes_map[position].append(new_index)
                        positions.add(position) # Only add position if a kept node exists there
                    # else: This boundary node was measured out, ignore it.
                else:
                    # No measurement, use original index
                    boundary_nodes_map[position].append(original_phase_space_index)
                    positions.add(position)
            else:
                # Optional: Add a warning if a boundary node is missing the position attribute
                # Avoid warning if the node wasn't kept anyway
                if kept_indices_lookup is None or original_phase_space_index in kept_indices_lookup:
                    print(f"Warning: Boundary node {node} is missing 'position_in_boundary' attribute.")

    # Sort the node indices within each position list
    for pos in boundary_nodes_map:
        boundary_nodes_map[pos].sort()

    # Filter out positions that might have been added initially but ended up with no kept nodes
    # (Shouldn't happen with current logic, but good practice)
    final_boundary_nodes_map = {pos: indices for pos, indices in boundary_nodes_map.items() if indices}
    unique_sorted_positions = sorted(list(final_boundary_nodes_map.keys()))

    return dict(final_boundary_nodes_map), unique_sorted_positions



import numpy as np

def calculate_jacobi_transformation_matrix(masses):
    """
    Calculates the 2N x 2N symplectic transformation matrix M for
    transforming from individual particle coordinates (x_i, p_i) to
    center-of-mass and Jacobi relative coordinates (R_CM, P_CM, rho_k, pi_k).

    Args:
        masses (list or np.ndarray): A list or NumPy array of N particle masses.

    Returns:
        np.ndarray: The 2N x 2N transformation matrix M.
    """
    masses = np.array(masses, dtype=float)
    n = len(masses)
    if n == 0:
        return np.array([[]])
    if np.any(masses <= 0):
        print("Warning: Masses should generally be positive.")

    m_tot = np.sum(masses)
    if m_tot == 0:
         raise ValueError("Total mass cannot be zero.")

    # Initialize N x N blocks A and D
    A = np.zeros((n, n))
    D = np.zeros((n, n))

    # --- Fill A Matrix (X' = AX) ---
    # Row 0: R_CM = sum(m_j * x_j) / M_tot
    A[0, :] = masses / m_tot

    # Rows 1 to N-1: rho_k = x_{k+1} - sum(m_j * x_j) / sum(m_j) [for j=1..k]
    # Corresponds to A[k, :] where k is row index (0-based)
    current_m_sum = 0.0
    for k in range(n - 1): # k runs from 0 to n-2
        current_m_sum += masses[k]
        if current_m_sum == 0:
            raise ValueError(f"Sum of first {k+1} masses is zero, division by zero.")

        # Coefficient of x_{k+1} (column k+1) is 1
        A[k + 1, k + 1] = 1.0
        # Coefficients of x_j for j=0..k (columns 0..k)
        for j in range(k + 1):
            A[k + 1, j] -= masses[j] / current_m_sum

    # --- Fill D Matrix (P' = DP) ---
    # Row 0: P_CM = sum(p_j)
    D[0, :] = 1.0

    # Rows 1 to N-1: pi_k = (sum_1^k(m_j) * p_{k+1} - m_{k+1} * sum_1^k(p_j)) / sum_1^{k+1}(m_j)
    # Corresponds to D[k, :] where k is row index (0-based)
    current_m_sum = 0.0
    for k in range(n - 1): # k runs from 0 to n-2
        m_k_plus_1 = masses[k+1]
        m_sum_partial = current_m_sum + masses[k] # sum m_1 to m_{k+1}
        m_sum_total = m_sum_partial + m_k_plus_1 # sum m_1 to m_{k+2} -> Mistake here, check indices
        # Let's retry index logic matching the formula using k_jacobi = 1..N-1
        # We fill row i_prime = 1..N-1
        # i_prime = k_jacobi corresponds to rho_{k_jacobi}, pi_{k_jacobi}

        # Reset and recalculate sums based on i_prime = 1 to n-1 (row index)
        # This corresponds to jacobi index k = i_prime - 1
        # We need sum up to k (i_prime -1) and sum up to k+1 (i_prime)

    m_sum_partial = 0.0 # Sum m_1 .. m_k
    for i_prime in range(1, n): # i_prime runs 1 to n-1 (row index)
         # Corresponds to Jacobi index k = i_prime - 1
         k = i_prime - 1
         m_k_plus_1 = masses[k + 1] # mass m_{k+1}
         m_sum_1_to_k = np.sum(masses[:k+1]) # Sum m_1 to m_{k+1}
         m_sum_1_to_k_plus_1 = np.sum(masses[:k+2]) # Sum m_1 to m_{k+2}

         if m_sum_1_to_k_plus_1 == 0:
             raise ValueError(f"Sum of first {k+2} masses is zero, division by zero.")

         # Coefficient of p_{k+1} (column k+1)
         D[i_prime, k + 1] = m_sum_1_to_k / m_sum_1_to_k_plus_1

         # Coefficients of p_j for j=0..k (columns 0..k)
         coeff_pj = -m_k_plus_1 / m_sum_1_to_k_plus_1
         for j in range(k + 1):
             D[i_prime, j] = coeff_pj

    # --- Assemble the full 2N x 2N Matrix M ---
    M_matrix = np.zeros((2 * n, 2 * n))

    for i_prime in range(n):
        for j_prime in range(n):
            # Indices in the 2N x 2N matrix
            i_x = 2 * i_prime
            i_p = 2 * i_prime + 1
            j_x = 2 * j_prime
            j_p = 2 * j_prime + 1

            # Place elements from A and D
            M_matrix[i_x, j_x] = A[i_prime, j_prime]
            M_matrix[i_p, j_p] = D[i_prime, j_prime]
            # B and C blocks are implicitly zero from initialization

    return M_matrix

def canon_cycle_4(c):
    """Returns the canonical form of a 4-cycle for de-duplication.

    Given a 4-cycle [u, a, v, b], computes all 8 equivalent representations
    (4 rotations and 4 rotations of the reverse) and returns the
    lexicographically minimal tuple. This ensures that cycles differing only
    by rotation or direction map to the same canonical representative.

    Args:
        c: A sequence of 4 elements representing a cycle [u, a, v, b].

    Returns:
        The lexicographically minimal tuple among all rotations and reversals.

    Example:
        >>> canon_cycle_4([2, 1, 3, 0])
        (0, 2, 1, 3)  # Represents rotation/reversal of the input
    """
    c = list(c)
    rots = [tuple(c[i:]+c[:i]) for i in range(4)]
    r = list(reversed(c))
    rotsR = [tuple(r[i:]+r[:i]) for i in range(4)]
    return min(rots + rotsR)

def chordless_4cycles_nodes(G: nx.Graph):
    """
    All chordless 4-cycles {u,a,v,b} with edges u-a, a-v, v-b, b-u, and NO chords u-v, a-b.
    Uses opposite-corner pairs (u,v) that are NOT adjacent and have two distinct common neighbors.
    De-duplicates via canonical cyclic form.
    """
    C = set()
    neigh = {n: set(G[n]) for n in G.nodes()}
    nodes = list(G.nodes())
    # unordered non-edges as opposite corners
    for i, u in enumerate(nodes):
        Nu = neigh[u]
        for v in nodes[i+1:]:
            if v in Nu:  # skip edges; opposite corners must be non-adjacent (chordless)
                continue
            S = Nu & neigh[v]          # common neighbors = the other two corners
            for a, b in it.combinations(sorted(S), 2):
                if a == b or a in (u, v) or b in (u, v):
                    continue
                # enforce CHORDLESS: the other opposite pair (a,b) must also be non-adjacent
                if b in neigh[a]:
                    continue
                cyc = canon_cycle_4([u, a, v, b])
                C.add(cyc)
    return list(C)

def triangles_nodes(G):
    """All 3-cycles via cliques; fast and complete for triangles."""
    tris = []
    for c in nx.enumerate_all_cliques(G):
        if len(c) == 3:
            u, v, w = c
            # canonicalize triangle (smallest rotation ignoring direction)
            rots = [tuple(c[i:]+c[:i]) for i in range(3)]
            r = list(reversed(c))
            rotsR = [tuple(r[i:]+r[:i]) for i in range(3)]
            tris.append(min(rots + rotsR))
        elif len(c) > 3:
            break
    # dedup just in case
    return sorted(set(tris))